<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<!-- Mirrored from openhome.cc/Gossip/Scala/TryExpression.html by HTTrack Website Copier/3.x [XR&CO'2008], Sun, 28 Jul 2013 09:11:14 GMT -->
<head>







  
  
  
  
  
  
  
  <link rel="stylesheet" href="css/stdlayout.css" type="text/css">







  
  
  
  
  
  
  
  <link rel="stylesheet" href="css/print.css" type="text/css">







  
  
  
  
  
  
  
  <meta content="text/html; charset=Big5" http-equiv="content-type">







  
  
  
  
  
  
  
  <title>try 運算式</title></head>
<body>







<h3><a href="../index.html">From
Gossip@Openhome</a></h3>







<h1><a href="index-2.html">Scala Gossip: try 運算式</a></h1>

<table style="text-align: left; width: 946px; height: 32px;" border="0" cellpadding="0" cellspacing="0">

  <tbody>

    <tr>

      <td style="vertical-align: top; width: 250px; text-align: center;"><script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
      </script>
      <script type="text/javascript" src="../../../pagead2.googlesyndication.com/pagead/show_ads.js">
      </script><br>
      <br>
      <script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
      </script>
      <script type="text/javascript" src="../../../pagead2.googlesyndication.com/pagead/show_ads.js">
      </script><br><br><center> </center></td>

      <td style="vertical-align: top; width: 690px; text-align: left;"><small>如果你撰寫了這段程式：<br></small><div style="margin-left: 40px;"><small style="font-family: Courier New,Courier,monospace; font-weight: bold;">val filename = args(0)</small><br></div><small><br>使
用者如果沒有提供命令列引數，則args的長度會是0，存取索引0就會發生超出陣列索引範圍的錯誤，在Scala中，會丟出
java.lang.ArrayIndexOutOfBoundsException。你可以使用isEmpty來測試args是否為空，在沒有提供引數
時建立</small><small>例外物件</small><small>丟出以提供錯誤訊息：<br></small><div style="margin-left: 40px;"><small><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">if(args.isEmpty)<br>&nbsp;&nbsp;&nbsp; throw new IllegalArgumentException("必須提供引數")<br><br>val filename = args(0)<br>// 繼續程式...<br></span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;"></span></small><br></div><small><br><span style="font-family: Times New Roman,Times,serif;">另一個方式是使用try...catch語句，在使用者沒有提供引數時，於catch中捕捉例外並顯示錯誤訊息：<br></span></small><div style="margin-left: 40px;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">try {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; val filename = args(0)</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; // 繼續程式...</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">catch {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; case ex: ArrayIndexOutOfBoundsException =&gt; println("必須提供引數")</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></small><br><small><span style="font-family: Times New Roman,Times,serif;"></span></small></div><small><span style="font-family: Times New Roman,Times,serif;"><br>程式會嘗試取得args(0)，如果丟出例外，而在catch中有撰寫對應的case比對，則會執行對應的處理程式。如果有多個例外類似要比對，則可以撰寫多個case，如果最後有一定得處理的程式，則可以撰寫finally區塊，例如：<br></span></small><div style="margin-left: 40px;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">import java.io._</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">try {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; val reader = new FileReader(args(0))</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; try {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // 作一些處理</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; catch {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case ex: IOException =&gt; println("發生 IO 錯誤")</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; finally {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; reader.close()</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">catch {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; case ex: ArrayIndexOutOfBoundsException =&gt; println("必須提供引數")</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; case ex: FileNotFoundException =&gt; println("找不到檔案：" + args(0))</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></small><br><small><span style="font-family: Times New Roman,Times,serif;"></span></small></div><small><span style="font-family: Times New Roman,Times,serif;"><br>在Scala中，並不要求你得處理受檢例外（Checked Exception）（參考Java的 </span></small><small><a href="../JavaGossip-V1/ExceptionHierarchy.htm">例
外的繼承架構</a></small><small><span style="font-family: Times New Roman,Times,serif;">），
你只需針對感興趣或有能力處理的例外加以捕捉並處理即可，如果在例外發生的當時情境下無力處理，你什麼事都不用作（不用寫try...catch也不用在
函式或方法上用throws宣告），將處理留給後續的呼叫者來善後（在Java中，受檢例外是由編譯器進行檢查，Scala編譯器不檢查受檢例外，事實
上，Scala也沒有throws關鍵字。如果你要讓某個方法在編譯後產生的位元碼中，有Java中throws宣告，以便給Java程式使用時可以得到
受檢例外檢查機制，則可以使用@throws標注，標注的使用之後還會說明）。<br><br>在Scala中，try...catch...finally是運算式，所以會有運算結果，例如你可以撰寫這樣的程式碼：<br></span></small><div style="margin-left: 40px;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">val filename = </span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; try {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; args(0)</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; catch {</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case ex: ArrayIndexOutOfBoundsException =&gt; "default.properties"</span></small><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span></small><br style="font-weight: bold;"><small><span style="font-family: Times New Roman,Times,serif;"></span></small></div><small><span style="font-family: Times New Roman,Times,serif;"><br>如
果有提供命令列引數，則將filename設定為所提供的值，否則就是設定為default.properties。你也可以在finally中提供傳回
值，不過並不鼓勵，因為finally中基本上是用來關閉、釋放某些資源或作些善後動作。如果你要在finally中提供傳回值，要注意一下以下兩個程式
片段的不同：<br></span></small><div style="margin-left: 40px;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">def doSome = try { 1 } finally { 2 }</span></small><br><small><span style="font-family: Times New Roman,Times,serif;"></span></small></div><small><span style="font-family: Times New Roman,Times,serif;"><br>如果你呼叫doSome()，則以上程式片段會傳回try區塊中的1，但如果是：<br></span></small><div style="margin-left: 40px;"><small style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">def doSome: Int = try { return 1 } finally { return 2 }</span></small><br><small><span style="font-family: Times New Roman,Times,serif;"></span></small></div><small><span style="font-family: Times New Roman,Times,serif;"><br>因
為你明確地使用return，這個程式片段會傳回2（這個行為與Java是相同的）。如先前所提到的，在finally中並不建議有傳回值，而僅用於關
閉、釋放資源或作些善後動作（明確地使用return在Scala中也是不鼓勵的，因為容易破壞程式的結構，在Scala中使用return就無法使用類
型推斷，像以上定義函式時，就得明確定義函式的傳回值型態，另外，return在Scala中只能用於函式之中）。<br><br>在Scala中處理例外，要注意一下例外比對的順序，例如：<br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">val filename =</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; try {</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; args(0)</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; catch {</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case ex: Exception =&gt; // 作一些處理</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case ex: ArrayIndexOutOfBoundsException =&gt; // 作一些處理</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; }</span><br><br></span></small><small></small><small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;"></span></span></small><small style="font-family: Courier New,Courier,monospace; font-weight: bold;"></small><small>由於Exception是ArrayIndexOutOfBoundsException的父類別，所以這個程式片段，只會符到到第一個Exception，第二個</small><small>ArrayIndexOutOfBoundsException永遠不會被比對到，Scala不會提出警訊（Java的編譯器會對這部份作檢查），程式會照常執行。</small><br><small><br></small></td>

    </tr>

  </tbody>
</table>

<br>
<br>

<br>

<br>







<script src="../../../www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-143766-1";
urchinTracker();
</script></body>
<!-- Mirrored from openhome.cc/Gossip/Scala/TryExpression.html by HTTrack Website Copier/3.x [XR&CO'2008], Sun, 28 Jul 2013 09:11:14 GMT -->
</html>